In [1]:
import pandas as pd

df = pd.read_csv('/kaggle/working/SIEM_data.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 419382 entries, 0 to 419381
Data columns (total 19 columns):
 #   Column                Non-Null Count   Dtype 
---  ------                --------------   ----- 
 0   Unnamed: 0            419382 non-null  int64 
 1   AlertTitle            419382 non-null  int64 
 2   Sha256                419382 non-null  int64 
 3   IpAddress             419382 non-null  int64 
 4   Url                   419382 non-null  int64 
 5   AccountUpn            419382 non-null  int64 
 6   AccountName           419382 non-null  int64 
 7   DeviceName            419382 non-null  int64 
 8   RegistryKey           419382 non-null  int64 
 9   RegistryValueName     419382 non-null  int64 
 10  RegistryValueData     419382 non-null  int64 
 11  ApplicationName       419382 non-null  int64 
 12  FileName              419382 non-null  int64 
 13  FolderPath            419382 non-null  int64 
 14  ResourceIdName        419382 non-null  int64 
 15  OSFamily         

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import numpy as np

In [3]:
TARGET = 'SuspicionLevel_label'
features_to_drop = ['Unnamed: 0', 'SuspicionLevel', TARGET]

In [4]:
X = df.drop(columns=features_to_drop)
y = df[TARGET]

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

In [7]:
print(f"Training set size: {len(X_train)} samples")
print(f"Testing set size: {len(X_test)} samples")
print("-" * 50)

Training set size: 293567 samples
Testing set size: 125815 samples
--------------------------------------------------


In [8]:
def evaluate_model(model, X_train, y_train, X_test, y_test, model_name):
    print(f"--- Training {model_name} ---")
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)    
    accuracy = accuracy_score(y_test, y_pred)
    print(f"\n{model_name} Accuracy Score: {accuracy:.4f}")
    
    print(f"\n{model_name} Classification Report:")
    print(classification_report(y_test, y_pred, zero_division=0))

    cm = confusion_matrix(y_test, y_pred)
    print(f"\n{model_name} Confusion Matrix:")
    print(cm)
    
    print("-" * 50)

In [9]:
knn_classifier = KNeighborsClassifier(n_neighbors=5)
evaluate_model(knn_classifier, X_train, y_train, X_test, y_test, "K-Nearest Neighbors (KNN)")

--- Training K-Nearest Neighbors (KNN) ---

K-Nearest Neighbors (KNN) Accuracy Score: 0.9987

K-Nearest Neighbors (KNN) Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       147
           1       1.00      1.00      1.00    125668

    accuracy                           1.00    125815
   macro avg       0.50      0.50      0.50    125815
weighted avg       1.00      1.00      1.00    125815


K-Nearest Neighbors (KNN) Confusion Matrix:
[[     0    147]
 [    11 125657]]
--------------------------------------------------


In [10]:
dt_classifier = DecisionTreeClassifier(random_state=42)
evaluate_model(dt_classifier, X_train, y_train, X_test, y_test, "Decision Tree (DT)")

--- Training Decision Tree (DT) ---

Decision Tree (DT) Accuracy Score: 0.9978

Decision Tree (DT) Classification Report:
              precision    recall  f1-score   support

           0       0.14      0.18      0.16       147
           1       1.00      1.00      1.00    125668

    accuracy                           1.00    125815
   macro avg       0.57      0.59      0.58    125815
weighted avg       1.00      1.00      1.00    125815


Decision Tree (DT) Confusion Matrix:
[[    26    121]
 [   155 125513]]
--------------------------------------------------


In [11]:
rf_classifier = RandomForestClassifier(n_estimators=50, random_state=42, n_jobs=-1)
evaluate_model(rf_classifier, X_train, y_train, X_test, y_test, "Random Forest (RF)")

--- Training Random Forest (RF) ---

Random Forest (RF) Accuracy Score: 0.9982

Random Forest (RF) Classification Report:
              precision    recall  f1-score   support

           0       0.09      0.06      0.07       147
           1       1.00      1.00      1.00    125668

    accuracy                           1.00    125815
   macro avg       0.54      0.53      0.54    125815
weighted avg       1.00      1.00      1.00    125815


Random Forest (RF) Confusion Matrix:
[[     9    138]
 [    90 125578]]
--------------------------------------------------
